// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDobN8xF0vIrruJETufZ9PXDEiOKtpsuL4',
    appId: '1:268710115805:web:abac459bad9bd1ae12de34',
    messagingSenderId: '268710115805',
    projectId: 'test-app-d55cb',
    authDomain: 'test-app-d55cb.firebaseapp.com',
    storageBucket: 'test-app-d55cb.firebasestorage.app',
    measurementId: 'G-6TEMDC5PE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKX6aQAsZwvNGSfl-zO9-zUxNusEiR1io',
    appId: '1:268710115805:android:6f437376935d18c912de34',
    messagingSenderId: '268710115805',
    projectId: 'test-app-d55cb',
    storageBucket: 'test-app-d55cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZmVF74m8w1EWK4uH0nIAM13qAJUt0l4',
    appId: '1:268710115805:ios:0f852c38c8333be012de34',
    messagingSenderId: '268710115805',
    projectId: 'test-app-d55cb',
    storageBucket: 'test-app-d55cb.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDobN8xF0vIrruJETufZ9PXDEiOKtpsuL4',
    appId: '1:268710115805:web:90d46d1249eaa48612de34',
    messagingSenderId: '268710115805',
    projectId: 'test-app-d55cb',
    authDomain: 'test-app-d55cb.firebaseapp.com',
    storageBucket: 'test-app-d55cb.firebasestorage.app',
    measurementId: 'G-B1CBCRQMEV',
  );
}
